### ISSUE TITLE
Type 'MetalEffectPIX' does not conform to protocol 'NODEMetal'

### ISSUE THREAD

**Issue by brightfuture** [heestand-xyz/Noise#1]
this error message is popping up everywhere

**Comment by just-doit** [comment]
I'm getting the same error.

**Comment by heestand-xyz** [comment]
Sorry about that, I'll try to look into it, tho please check out [AsyncGraphics](https://github.com/heestand-xyz/AsyncGraphics), it's got all the noise shaders: [Noise for Graphic](https://heestand-xyz.github.io/AsyncGraphics-Docs/documentation/asyncgraphics/graphic/noise(offset:depth:scale:octaves:seed:resolution:options:)) & [Noise for View](https://heestand-xyz.github.io/AsyncGraphics-Docs/documentation/asyncgraphics/agnoise)

**Comment by just-doit** [comment]
No problem. Meanwhile I found this fork: https://github.com/AdelaideSky/Noise.
It seems to just have fixed this error. I haven't looked into the commits though.
Thanks for the package, btw. ;-)

**Comment by heestand-xyz** [comment]
Version `2.0.0` is now available with a fix!
It's using the new SwiftUI Metal shaders.
