### ISSUE TITLE
Random with speed?

### ISSUE THREAD

**Issue by zshannon** [heestand-xyz/Noise#3]
Hey there, this library is fantastic thanks for sharing it! I'm wondering what it would take to get the speed parameter to affect the random style, is that something that's easy to patch on?

**Comment by heestand-xyz** [comment]
Hi, it's a good idea!
Currently the random noise does not get affected by speed.
I'll see if I can add this!

I'm guessing you are looking for the TV noise effect.
To make this you can use the seed modifier like this:

```swift
import SwiftUI
import Noise

struct ContentView: View {
    
    @State private var startTime: Date = .now
    
    var body: some View {
        TimelineView(.animation) { context in
            let seconds = startTime.distance(to: context.date)
            let milliseconds = Int(seconds * 1_000)
            Noise(style: .random)
                .monochrome()
                .seed(milliseconds)
        }
    }
}
```

**Comment by heestand-xyz** [comment]
I've now updated the package to support speed for random noise in version `2.0.2`.
Now you can simple call it like this:
```swift
Noise(style: .random, speed: 100)
```

**Comment by zshannon** [comment]
Wow! You are awesome for taking this up so quickly!! I should've been more specific about what I'm seeking, it's not the CRT TV "snow" as much as a very fine grain version of `.noisy`. Different from what you shipped here in that the pixels would be "moving" not randomly respawning. Is that achievable?

**Comment by heestand-xyz** [comment]
Check out the new `.scale(2.0)` modifier in version `2.0.3`
